### ISSUE TITLE
In Firefox and IE pin is being show

### ISSUE THREAD

**Issue by esaramago** [fkranenburg/bootstrap-pincode-input#11] opened 2017-08-09 14:49 UTC
Firefox 54 for windows 8 and IE11 are not masking pin with discs.

**Comment by fkranenburg** [comment] 2017-08-09 17:35
Sorry, I can't reproduce. Could you make a fiddle of your code? Make sure you set `hidedigits `to `false`.

Did you try example number 2 of the demo page on both browsers? It seems to work in IE (w10) en Firefox 55.
http://fkranenburg.github.io/bootstrap-pincode-input/

**Comment by esaramago** [comment] 2017-08-09 17:54
You're right. I didn't check example 2.
The only problem is that, on mobile, it doesn't show the number keyboard.
Anyway, it works on iE and Firefox. You can close this issue.

**Comment by fkranenburg** [comment] 2017-08-09 18:50
You are right about that problem. That is a tricky one. I'll close this and open a new issue about that problem.

**Closed by fkranenburg** 2017-08-09 18:50 UTC
