### ISSUE TITLE
Ignores keypresses, due to slow jumping to next field

### ISSUE THREAD

**Issue by onyxg** [fkranenburg/bootstrap-pincode-input#18] opened 2018-08-17 21:16 UTC
There appears to be a problem when you type really fast on the desktop version (multiple input boxes)

**Comment by fkranenburg** [comment] 2018-08-18 08:26
I can't reproduce. What browser are you using?

**Comment by fkranenburg** [comment] 2018-08-29 17:31
I'm closing this since I still can't reproduce. Without any further information it is impossible to investigate this. To me it looks like a local browser / hardware related issue.

**Closed by fkranenburg** 2018-08-29 17:31 UTC
